### ISSUE TITLE
Slow Detection Of New Stream Activity

### ISSUE THREAD

**Issue by ghost** [BasioMeusPuga/twitchy#10]
I'm getting a notification on my phone via Twitch app that a stream is online, and I can view the stream in my browser, but Twitchy doesn't detect the stream as online until several minutes later.

**Comment by BasioMeusPuga** [comment]
We rely on the Twitch API for telling us who's online. Unfortunately, since the API doesn't do instantaneous updates, this introduces a slight delay both at the start and at the end of a stream. This is unfixable.
The situation might improve with the v5 API (we're at v3). Or it might not.

What I could do is add a `--force` switch as an option. It'll essentially skip the checks and start the stream, being otherwise indistinguishable from normal operation. However, this will 1. Introduce errors when stuff isn't online / doesn't exist, and 2. Will have to rely on a secondary device (like your phone) to actually tell you when something is online. 3. Take away quality settings.

At this point, how about just going

    $ streamlink twitch.tv/<channel name> best --player mpv
