### ISSUE TITLE
A few random ideas and requests regarding a compact layout, colours etc

### ISSUE THREAD

**Issue by Hund** [BasioMeusPuga/twitchy#3]
First of all, it's great to see a TUI alternative to the now long dead project livestreamer-curses! It's so nice to be able to list only channels that live and not just hosting someone. :)

I have a few ideas though, I hope you don't mind. I also made a mockup to go with my ideas and I hope you like it and that this is something you would consider.

**1. Colours**

It would be nice to have optional colours and to be able to define them yourself. Colours is a nice way to make a lot of text more readable.

**2. Custom columns**

I don't care what game someone plays, but the someone else might. It would be able to choose what to display and not.

**3. Uptime**

I know it's possible to fetch the uptime, it would be nice to be able to see it. Since it would be a factor to consider when choosing to watch a stream.

**4. Comptact list**

It would be nice to have a option for a more comact list.

**5. Config file**

This is more like a demand than a request. :D I'd like to see an actual file I could edit myself. The wizard is a nice feature, if it's optional to use it or not when you try to run twitchy without an actual config.

**6. Option to disable chat**

I use IRC for the chatting and I'm probably not the only one. It would be nice it the chat could be optional.

![](http://i.imgur.com/nfVV2oZ.png)

Oh, btw. I copied the titles from twitchy and I don't know why it cut them off so short? Any ideas?

Cheers!

**Comment by BasioMeusPuga** [comment]
Hey. 
Most of what you're talking about is fairly doable. I just need a little clarification. I'll walk through what you've mentioned.

1. Colors
It's actually quite easy to allow coloring to be changed. But you should know that accounting for every color will be quite difficult unless I just outright expose the option to change the escape sequences I use. So it'll have to be Green / Blue / Orange etc.
Also, this won't work very well using a config wizard alone. So it'll have to come after I include the config file.

2. Columns
Yeah. This will take a little redoing. But it should be mostly possible. If (and when) I get around to this, it'll have to be towards the end; since I really don't see this working without a config file either.

3. Uptime
The Twitch API provides the uptime so, yes, we already have the value. I can see this happening when I redo the code for the custom columns. Speaking of, literally any other value that the API provides can also be made into its own column.

4. Compact list
I don't quite understand this. Compact how? What do you want to have the option to leave out? And include, for that matter.

5. Config file
I know I'm still keeping the wizard. What I can do is get it to write to a config file instead of the single database I use.
In the meantime, if you want to be able to edit the values by hand, I recommend sqlitebrowser or something similar. Everything is stored in the 'options' table in ~/.twitchy.db

The status message cut off is dependent on terminal width if you set it to AUTO during initial setup. I don't know why the 3rd string got attenuated so much when the others didn't. I'd recommend putting in an actual numeric value in the beginning and seeing what happens.

**Comment by Hund** [comment]
Cool. :)

Every color? Why not stick to the base 16 colors? Or am I misunderstanding something?

Regarding a compact layout, just look at my mockup. Every stream I on one line and they're not sorted by game and such. If 5 streamers play 5 different games, then we're up at 10 lines. That's a lot of unused space for me.

Keep up the good work!

**Comment by BasioMeusPuga** [comment]
Alright. This is fine. I'll see what I can do. Watch this space for more.

**Comment by BasioMeusPuga** [comment]
I think everything is done. I'll put in some sanity checks for the options when I can. Some fringe case formatting may have come undone, but that's fixable. Let me know if you find anything show stopping.

P.s. If something gets messed up:

    $ twitchy --configure

**Comment by Hund** [comment]
It looks good! Goog job! :)

It would be nice if there was one empty line between the text "Checking X channel(s)..." and the list of streams.

The colors doesn't seems to be working for me, kinda. I could change to red, but when I changed to blue I got a gray or something. But I'm not sure if that's a issue on my side, because the colors in rTorrent stopped working the other day as well, on both my machines with Arch Linux :|

The options `ColumnNames = True` doesn't work for me.

And it would be nice if the config and the databas could move to a folder in your config path; `$CONFIG/twitchy/`.

And how is the auto update feature supose to work? I'm not sure if I'm misunderstanding it or if it doesn't work.

I hope you don't find me annoying! I'm just trying to help. :D

**Edit:** Ops. I always choose the one wrong button.

**Comment by BasioMeusPuga** [comment]
Seriously, any suggestions are welcome.

I haven't implemented the `ColumnNames` option yet. I'm not sure about leaving a line in the default view, but I can definitely put one whenever `ColumnNames` gets written.

The colors thing I'm not sure about. I checked the escape codes and they are what they should be. I'll see if there's an alternate way to color console applications. But I won't hold my breath on that one.

I have been thinking about moving all my files into one of the XDG dirs, yes. In fact, that is where I will go next.

I assume your installation was through the AUR? In that case, you really don't need to update using the script.

**Comment by Hund** [comment]
Okey. :) 

I was refering to `CheckInterval`, I'm sorry if I wasn't clear enough. Is that suppose to update the streams every X minute or so?

**Comment by BasioMeusPuga** [comment]
`CheckInterval` is definitely working. It checks every x seconds to see if someone came online. You kinda have to use it with the -n switch.

I should probably write this down somewhere in the config file. :|

**Comment by Hund** [comment]
Ah! I didn't know that. Awesome! :D

**Comment by BasioMeusPuga** [comment]
So everything is done. I think. The columns don't auto resize yet, but as long as the 2nd column doesn't have some ode to loquacity in it, we should be fine.

Tell me if you think of anything else. I'm closing this issue for now.

**Comment by Hund** [comment]
The colors works on my second computer only, but I assume that's a issue on my side. :)

The only thing I've noticed is that I get extra spacing when the terminal is not wide enough. I tried changing the value for ` TruncateStatus`, but it didn't help.

![twitchy](https://cloud.githubusercontent.com/assets/320498/25679883/3880d11c-304f-11e7-8877-a82cd8ab465d.png)

**Comment by BasioMeusPuga** [comment]
I think this should be fixed now. There was some (recklessly large) blank space after the status message that was getting pushed to the next line.

**Comment by Hund** [comment]
Thanks! It seems to be working now. :)
