### ISSUE TITLE
Rather a question than a issiu --non-interactive

### ISSUE THREAD

**Issue by yuri0r** [BasioMeusPuga/twitchy#31]
the output of --non-interactive consists of 4 coma separated parts e.g.

`Overwatch,Overwatch,mL7_ow,ml7_ow`

for me the first and last two parts are always the same, i guess its intentional and maybe the streamer hasn't set up a custom title or whatever.
question is basically what each part of the string is representing?

**Comment by BasioMeusPuga** [comment]
Please see the config file for your installation of twitchy. Especially the non-interactive section. 

Long story short, by default it outputs the alternate and the real names together (separated by the delimiter character) .You may then select whichever one you want. You'll need to make an alternate name in order to see a different output. Try it with `twitchy -an`.
